artifact:
  id: Middleware.DbContextConfigurations
  version: 1

layer: Middleware
type: DbContextConfigurations
variant: null
description: "Generates a middleware DbContextConfigurations"

model:
  source: metadata

generation:
  enabled: true
  target:
    namespacePattern: "{{projectConvention}}.Middleware.AddServices"
    path: "src\\{{projectConvention}}.Middleware\\AddServices"
    filename: "AddDbContextConfigurations.cs"
  template:
    engine: razor
    file: "Middleware/DbContextConfigurations"

reading:
  enabled: false