artifact:
  id: Middleware.DomainServicesConfigurations
  version: 1

layer: Middleware
type: DomainServicesConfigurations
variant: null
description: "Generates a middleware DomainServicesConfigurations"

model:
  source: metadata

generation:
  enabled: true
  target:
    namespacePattern: "{{projectConvention}}.Middleware.AddServices"
    path: "src\\{{projectConvention}}.Middleware\\AddServices"
    filename: "AddDomainServicesConfigurations.cs"
  template:
    engine: razor
    file: "Middleware/DomainServicesConfigurations"

reading:
  enabled: false